### PR TITLE
Some basic unit tests

### PR DESCRIPTION
**Pull request by peterwilsoncc**

### CODE REVIEW

**Comment by rmccue** [comment]
> `'__fake_schedule'` is returned on single events instead of `''`, @rmccue is it a problem if these are removed from single events?

Is this a regression? It should be not set or set to `null` IIRC

**Comment by rmccue** [comment]
> Is this a regression? It should be not set or set to `null` IIRC

tl;dr no, but let's make it `null` for non-recurring.

**Comment by peterwilsoncc** [comment]
@rmccue 

The core cron test suite now passes with Cavalcade, changes in this PR:

* Add core test suite
* Removed sniffs because they're not passing
* cron array is key sorted to ensure it's returned in the correct order.
* schedule  defaults to `false` to match [core](https://github.com/WordPress/wordpress-develop/blob/master/src/wp-includes/cron.php#L34-L45)

**Comment by peterwilsoncc** [comment]
The test suite install only downloads the required directories from WP Core's suite (`includes` and `data`) so I've added an extra step to download the cron tests and copy it into the Cavalcade test directory.

**Pull request merged**
