### PR TITLE
Add a `LIMIT` clause to `wp cavalcade jobs` queries

### LINKED ISSUE #34: `wp cavalcade jobs` needs a sane `LIMIT`
Running `wp cavalcade jobs --status=completed` will result in the command fetching potentially millions of rows, which takes forever (if it even finishes) and doesn't provide meaningful results to the user.

A default limit of `10` or `20` and a `--limit` parameter seems like a good solution.

### PR DESCRIPTION
**Pull request by iandunn**
Fixes #34

### CODE REVIEW

**Comment by rmccue** [comment]
Can we also add a `--page=<page>` here? If we're going to use `LIMIT`, we should allow `OFFSET` too.

**Comment by iandunn** [comment]
Makes sense, I can probably add that tomorrow.

**Comment by iandunn** [comment]
b89ddc3 adds the `page` parameter.

**Comment by rmccue** [comment]
Thanks a bunch!

**Pull request merged**
